import { Kysely, PostgresDialect } from 'kysely';
import pg from 'pg';
import type { Database } from './types.js';

const { Pool } = pg;

const BROADWAY_SHOWS = [
  {
    title: 'Hamilton',
    description: 'An American Musical is a sung-and-rapped-through musical about the life of American Founding Father Alexander Hamilton.',
    opening_date: '2015-08-06',
    closing_date: null,
    theater: 'Richard Rodgers Theatre',
    composer: 'Lin-Manuel Miranda',
    lyricist: 'Lin-Manuel Miranda',
    book_writer: 'Lin-Manuel Miranda',
    director: 'Thomas Kail',
    music_director: 'Alex Lacamoire',
    choreographer: 'Andy Blankenbuehler',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'Wicked',
    description: 'The untold true story of the Witches of Oz. Long before Dorothy drops in, two other girls meet in the land of Oz. One, born with emerald-green skin, is smart, fiery, and misunderstood. The other is beautiful, ambitious, and very popular.',
    opening_date: '2003-10-30',
    closing_date: null,
    theater: 'Gershwin Theatre',
    composer: 'Stephen Schwartz',
    lyricist: 'Stephen Schwartz',
    book_writer: 'Winnie Holzman',
    director: 'Joe Mantello',
    music_director: 'Stephen Oremus',
    choreographer: 'Wayne Cilento',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'The Phantom of the Opera',
    description: 'A disfigured musical genius, hidden away in the Paris Opera House, terrorizes the opera company for the unwitting benefit of a young protegee whom he trains and loves.',
    opening_date: '1988-01-26',
    closing_date: '2023-04-16',
    theater: 'Majestic Theatre',
    composer: 'Andrew Lloyd Webber',
    lyricist: 'Charles Hart',
    book_writer: 'Richard Stilgoe',
    director: 'Harold Prince',
    music_director: null,
    choreographer: 'Gillian Lynne',
    is_currently_running: false,
    category: 'musical',
  },
  {
    title: 'The Lion King',
    description: 'Giraffes strut, birds swoop, gazelles leap. The entire Serengeti comes to life and as the music soars, Pride Rock slowly emerges from the mist. This is Disney\'s The Lion King.',
    opening_date: '1997-11-13',
    closing_date: null,
    theater: 'Minskoff Theatre',
    composer: 'Elton John',
    lyricist: 'Tim Rice',
    book_writer: 'Roger Allers',
    director: 'Julie Taymor',
    music_director: 'Robert Elhai',
    choreographer: 'Garth Fagan',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'Chicago',
    description: 'Set amidst the razzle-dazzle decadence of the 1920s, Chicago is the story of Roxie Hart, a housewife and nightclub dancer who maliciously murders her on-the-side lover after he threatens to walk out on her.',
    opening_date: '1996-11-14',
    closing_date: null,
    theater: 'Ambassador Theatre',
    composer: 'John Kander',
    lyricist: 'Fred Ebb',
    book_writer: 'Fred Ebb',
    director: 'Walter Bobbie',
    music_director: 'Rob Fisher',
    choreographer: 'Ann Reinking',
    is_currently_running: true,
    category: 'revival',
  },
  {
    title: 'Les Miserables',
    description: 'In 19th century France, Jean Valjean is released from years of unjust imprisonment, but finds nothing in store for him but mistrust and mistreatment.',
    opening_date: '1987-03-12',
    closing_date: '2016-09-04',
    theater: 'Imperial Theatre',
    composer: 'Claude-Michel Schonberg',
    lyricist: 'Herbert Kretzmer',
    book_writer: 'Alain Boublil',
    director: 'Trevor Nunn',
    music_director: null,
    choreographer: null,
    is_currently_running: false,
    category: 'musical',
  },
  {
    title: 'The Book of Mormon',
    description: 'The Book of Mormon follows two young Mormon missionaries who are sent to a remote village in Uganda to try to convert the citizens to the Mormon faith.',
    opening_date: '2011-03-24',
    closing_date: null,
    theater: 'Eugene O\'Neill Theatre',
    composer: 'Trey Parker',
    lyricist: 'Robert Lopez',
    book_writer: 'Trey Parker',
    director: 'Casey Nicholaw',
    music_director: 'Stephen Oremus',
    choreographer: 'Casey Nicholaw',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'Dear Evan Hansen',
    description: 'A letter that was never meant to be seen, a lie that was never meant to be told, a life he never dreamed he could have. Dear Evan Hansen is the deeply personal and profoundly contemporary musical about life and the way we live it.',
    opening_date: '2016-12-04',
    closing_date: '2022-09-18',
    theater: 'Music Box Theatre',
    composer: 'Benj Pasek',
    lyricist: 'Justin Paul',
    book_writer: 'Steven Levenson',
    director: 'Michael Greif',
    music_director: 'Ben Cohn',
    choreographer: 'Danny Mefford',
    is_currently_running: false,
    category: 'musical',
  },
  {
    title: 'Hadestown',
    description: 'Hadestown intertwines two mythic tales — that of young dreamers Orpheus and Eurydice, and that of King Hades and his wife Persephone — as it invites you on a journey to the underworld and back.',
    opening_date: '2019-04-17',
    closing_date: null,
    theater: 'Walter Kerr Theatre',
    composer: 'Anais Mitchell',
    lyricist: 'Anais Mitchell',
    book_writer: 'Anais Mitchell',
    director: 'Rachel Chavkin',
    music_director: 'Liam Robinson',
    choreographer: 'David Neumann',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'Moulin Rouge! The Musical',
    description: 'Enter a world of splendor and romance, of eye-popping excess, of glitz, grandeur and glory! A world where Bohemians and aristocrats rub elbows and revel in electrifying enchantment.',
    opening_date: '2019-07-25',
    closing_date: null,
    theater: 'Al Hirschfeld Theatre',
    composer: null,
    lyricist: null,
    book_writer: 'John Logan',
    director: 'Alex Timbers',
    music_director: 'Justin Levine',
    choreographer: 'Sonya Tayeh',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'Come From Away',
    description: 'The remarkable true story of 7,000 stranded passengers and the small town in Newfoundland that welcomed them. Cultures clashed and nerves ran high, but uneasiness turned into trust, music soared into the night, and gratitude grew into enduring friendships.',
    opening_date: '2017-03-12',
    closing_date: '2022-10-02',
    theater: 'Gerald Schoenfeld Theatre',
    composer: 'Irene Sankoff',
    lyricist: 'David Hein',
    book_writer: 'Irene Sankoff',
    director: 'Christopher Ashley',
    music_director: 'Ian Eisendrath',
    choreographer: 'Kelly Devine',
    is_currently_running: false,
    category: 'musical',
  },
  {
    title: 'A Chorus Line',
    description: 'A Chorus Line is a musical about Broadway dancers auditioning for spots on a chorus line. The show provides a glimpse into the personalities of the performers and the potential desperation involved in their careers.',
    opening_date: '1975-07-25',
    closing_date: '1990-04-28',
    theater: 'Shubert Theatre',
    composer: 'Marvin Hamlisch',
    lyricist: 'Edward Kleban',
    book_writer: 'James Kirkwood Jr.',
    director: 'Michael Bennett',
    music_director: null,
    choreographer: 'Michael Bennett',
    is_currently_running: false,
    category: 'musical',
  },
  {
    title: 'Rent',
    description: 'In the streets and cafes of New York\'s East Village, a group of Bohemians struggle to live and pay their rent. How do you measure a year in the life?',
    opening_date: '1996-04-29',
    closing_date: '2008-09-07',
    theater: 'Nederlander Theatre',
    composer: 'Jonathan Larson',
    lyricist: 'Jonathan Larson',
    book_writer: 'Jonathan Larson',
    director: 'Michael Greif',
    music_director: 'Tim Weil',
    choreographer: 'Marlies Yearby',
    is_currently_running: false,
    category: 'musical',
  },
  {
    title: 'West Side Story',
    description: 'From the first notes to the final breath, West Side Story is one of the most memorable musicals and greatest love stories of all time. Shakespeare\'s Romeo and Juliet is transplanted to 1950s New York City.',
    opening_date: '2020-02-20',
    closing_date: '2020-03-11',
    theater: 'Broadway Theatre',
    composer: 'Leonard Bernstein',
    lyricist: 'Stephen Sondheim',
    book_writer: 'Arthur Laurents',
    director: 'Ivo van Hove',
    music_director: null,
    choreographer: 'Anne Teresa De Keersmaeker',
    is_currently_running: false,
    category: 'revival',
  },
  {
    title: 'Beetlejuice',
    description: 'The ghost-with-the-most comes to life on stage in this hilarious new musical based on Tim Burton\'s dearly beloved film.',
    opening_date: '2019-04-25',
    closing_date: null,
    theater: 'Marquis Theatre',
    composer: 'Eddie Perfect',
    lyricist: 'Eddie Perfect',
    book_writer: 'Scott Brown',
    director: 'Alex Timbers',
    music_director: 'Kris Kukul',
    choreographer: 'Connor Gallagher',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'Six',
    description: 'From Tudor Queens to Pop Princesses, the six wives of Henry VIII take the mic to rematch their fates. These Queens get to tell their own stories in a modern pop concert.',
    opening_date: '2021-10-03',
    closing_date: null,
    theater: 'Lena Horne Theatre',
    composer: 'Toby Marlow',
    lyricist: 'Lucy Moss',
    book_writer: 'Toby Marlow',
    director: 'Lucy Moss',
    music_director: 'Joe Beighton',
    choreographer: 'Carrie-Anne Ingrouille',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'Company',
    description: 'At every turn, Bobby\'s well-meaning friends remind him that he\'s still single. But this time, Bobby is Bobbie. This gender-swapped revival breathes new life into Stephen Sondheim\'s masterpiece.',
    opening_date: '2021-12-09',
    closing_date: '2023-07-01',
    theater: 'Bernard B. Jacobs Theatre',
    composer: 'Stephen Sondheim',
    lyricist: 'Stephen Sondheim',
    book_writer: 'George Furth',
    director: 'Marianne Elliott',
    music_director: 'Joel Fram',
    choreographer: 'Liam Steel',
    is_currently_running: false,
    category: 'revival',
  },
  {
    title: 'Into the Woods',
    description: 'The Tony Award-winning musical classic by Stephen Sondheim and James Lapine intertwines the plots of several Brothers Grimm fairy tales.',
    opening_date: '2022-07-10',
    closing_date: '2023-08-06',
    theater: 'St. James Theatre',
    composer: 'Stephen Sondheim',
    lyricist: 'Stephen Sondheim',
    book_writer: 'James Lapine',
    director: 'Lear deBessonet',
    music_director: 'Rob Berman',
    choreographer: 'Lorin Latarro',
    is_currently_running: false,
    category: 'revival',
  },
  {
    title: 'The Great Gatsby',
    description: 'F. Scott Fitzgerald\'s classic American novel comes to life on the Broadway stage as a dazzling new musical.',
    opening_date: '2024-04-25',
    closing_date: null,
    theater: 'Broadway Theatre',
    composer: 'Jason Howland',
    lyricist: 'Nathan Tysen',
    book_writer: 'Kait Kerrigan',
    director: 'Marc Bruni',
    music_director: 'Jason Howland',
    choreographer: 'Dominique Kelley',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'Sweeney Todd',
    description: 'Attend the tale of Sweeney Todd! The demon barber of Fleet Street serves up Stephen Sondheim\'s masterful score in this thrilling revival.',
    opening_date: '2023-03-26',
    closing_date: '2024-09-08',
    theater: 'Lunt-Fontanne Theatre',
    composer: 'Stephen Sondheim',
    lyricist: 'Stephen Sondheim',
    book_writer: 'Hugh Wheeler',
    director: 'Thomas Kail',
    music_director: 'Alex Lacamoire',
    choreographer: 'Steven Hoggett',
    is_currently_running: false,
    category: 'revival',
  },
  {
    title: 'MJ: The Musical',
    description: 'MJ goes beyond the singular artistry of Michael Jackson to give audiences a rare look at the creative mind and collaborative spirit that catapulted Jackson into legendary status.',
    opening_date: '2022-02-01',
    closing_date: null,
    theater: 'Neil Simon Theatre',
    composer: null,
    lyricist: null,
    book_writer: 'Lynn Nottage',
    director: 'Christopher Wheeldon',
    music_director: 'Jason Michael Webb',
    choreographer: 'Christopher Wheeldon',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'Aladdin',
    description: 'Discover a whole new world at Disney\'s Aladdin, the hit Broadway musical. From the producer of The Lion King comes the timeless story of Aladdin.',
    opening_date: '2014-03-20',
    closing_date: null,
    theater: 'New Amsterdam Theatre',
    composer: 'Alan Menken',
    lyricist: 'Howard Ashman',
    book_writer: 'Chad Beguelin',
    director: 'Casey Nicholaw',
    music_director: 'Michael Kosarin',
    choreographer: 'Casey Nicholaw',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'Back to the Future: The Musical',
    description: 'When Marty McFly finds himself transported back to 1955 in a time machine built by the eccentric scientist Doc Brown, he accidentally changes the course of history.',
    opening_date: '2023-06-30',
    closing_date: null,
    theater: 'Winter Garden Theatre',
    composer: 'Alan Silvestri',
    lyricist: 'Glen Ballard',
    book_writer: 'Bob Gale',
    director: 'John Rando',
    music_director: 'Ethan Popp',
    choreographer: 'Chris Bailey',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'A Beautiful Noise',
    description: 'A Beautiful Noise, The Neil Diamond Musical tells the story of how a kid from Brooklyn became one of the most universally adored showmen of all time.',
    opening_date: '2022-12-04',
    closing_date: null,
    theater: 'Broadhurst Theatre',
    composer: null,
    lyricist: null,
    book_writer: 'Anthony McCarten',
    director: 'Michael Mayer',
    music_director: 'Sonny Paladino',
    choreographer: 'Steven Hoggett',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'The Outsiders',
    description: 'Stay gold. Based on S.E. Hinton\'s beloved novel, The Outsiders is a gripping new musical about finding the family you choose.',
    opening_date: '2024-04-11',
    closing_date: null,
    theater: 'Bernard B. Jacobs Theatre',
    composer: 'Jamestown Revival',
    lyricist: 'Jamestown Revival',
    book_writer: 'Adam Rapp',
    director: 'Danya Taymor',
    music_director: null,
    choreographer: 'Rick Kuperman',
    is_currently_running: true,
    category: 'musical',
  },
  {
    title: 'Cabaret at the Kit Kat Club',
    description: 'Welcome to the Kit Kat Club. This immersive new production of Cabaret transforms the August Wilson Theatre into the decadent world of 1929 Berlin.',
    opening_date: '2024-04-21',
    closing_date: null,
    theater: 'August Wilson Theatre',
    composer: 'John Kander',
    lyricist: 'Fred Ebb',
    book_writer: 'Joe Masteroff',
    director: 'Rebecca Frecknall',
    music_director: 'Jennifer Whyte',
    choreographer: 'Julia Cheng',
    is_currently_running: true,
    category: 'revival',
  },
  {
    title: 'Death of a Salesman',
    description: 'Arthur Miller\'s towering masterpiece returns to Broadway in a powerful new revival featuring a groundbreaking cast.',
    opening_date: '2022-10-09',
    closing_date: '2023-01-15',
    theater: 'Hudson Theatre',
    composer: null,
    lyricist: null,
    book_writer: null,
    director: 'Miranda Cromwell',
    music_director: null,
    choreographer: null,
    is_currently_running: false,
    category: 'play',
  },
  {
    title: 'The Minutes',
    description: 'Tracy Letts\' razor-sharp comedy looks beneath the surface of a seemingly typical city council meeting in a small American town.',
    opening_date: '2022-04-17',
    closing_date: '2022-07-24',
    theater: 'Studio 54',
    composer: null,
    lyricist: null,
    book_writer: null,
    director: 'Anna D. Shapiro',
    music_director: null,
    choreographer: null,
    is_currently_running: false,
    category: 'play',
  },
  {
    title: 'An Enemy of the People',
    description: 'Henrik Ibsen\'s masterwork about truth in an age of spin gets a thrilling new adaptation starring Jeremy Strong.',
    opening_date: '2024-03-18',
    closing_date: '2024-06-16',
    theater: 'Circle in the Square Theatre',
    composer: null,
    lyricist: null,
    book_writer: null,
    director: 'Sam Gold',
    music_director: null,
    choreographer: null,
    is_currently_running: false,
    category: 'play',
  },
  {
    title: 'Suffs',
    description: 'The story of the American women\'s suffrage movement. Suffs is a new musical by Shaina Taub that follows the courageous women who fought for the right to vote.',
    opening_date: '2024-04-18',
    closing_date: null,
    theater: 'Music Box Theatre',
    composer: 'Shaina Taub',
    lyricist: 'Shaina Taub',
    book_writer: 'Shaina Taub',
    director: 'Leigh Silverman',
    music_director: 'Andrea Grody',
    choreographer: 'Mayte Natalio',
    is_currently_running: true,
    category: 'musical',
  },
] as const;

export async function runSeed(externalDb?: Kysely<Database>) {
  const ownDb = !externalDb;
  let db: Kysely<Database>;

  if (externalDb) {
    db = externalDb;
  } else {
    const pool = new Pool({
      host: process.env['DB_HOST'] ?? 'localhost',
      port: parseInt(process.env['DB_PORT'] ?? '5432', 10),
      database: process.env['DB_NAME'] ?? 'curtaincall',
      user: process.env['DB_USER'] ?? 'postgres',
      password: process.env['DB_PASSWORD'] ?? '',
      ssl: process.env['DB_SSL'] === 'true'
        ? { rejectUnauthorized: false }
        : undefined,
    });

    db = new Kysely<Database>({
      dialect: new PostgresDialect({ pool }),
    });
  }

  console.log('Seeding shows...');

  for (const show of BROADWAY_SHOWS) {
    const existing = await db
      .selectFrom('shows')
      .where('title', '=', show.title)
      .selectAll()
      .executeTakeFirst();

    if (!existing) {
      await db
        .insertInto('shows')
        .values({
          title: show.title,
          description: show.description,
          opening_date: show.opening_date,
          closing_date: show.closing_date,
          theater: show.theater,
          image_url: null,
          composer: show.composer,
          lyricist: show.lyricist,
          book_writer: show.book_writer,
          director: show.director,
          music_director: show.music_director,
          choreographer: show.choreographer,
          is_currently_running: show.is_currently_running,
          category: show.category,
        })
        .execute();
      console.log(`  Created: ${show.title}`);
    } else {
      console.log(`  Skipped (exists): ${show.title}`);
    }
  }

  console.log(`Seeded ${BROADWAY_SHOWS.length} shows.`);
  if (ownDb) await db.destroy();
}

// Run directly when invoked as a script
const isDirectRun = import.meta.url === `file://${process.argv[1]}`;
if (isDirectRun) {
  runSeed().catch((err) => {
    console.error('Seed failed:', err);
    process.exit(1);
  });
}
